[boot]
systemd=true

[network]
generateHosts=true
generateResolvConf=false

[automount]
enabled = true
options = "metadata,uid=1000,gid=1000,umask=022,fmask=11"
mountFsTab = false

[user]
default = user

[gpu]
enabled = true

[interop]
enabled=false
appendWindowsPath=false

[time]
useWindowsTimezone = false
